name: workout_player
description: HēraKless - Workout Player

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  http: ^0.13.3
  logger: ^1.0.0
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.3

  # Firebase & Google
  firebase_storage: ^8.0.6
  firebase_core: ^1.1.1
  cloud_firestore: ^1.0.7
  cloud_functions: ^1.0.7
  firebase_auth: ^1.1.4
  firebase_crashlytics: ^2.0.3 # no web
  firebase_analytics: ^8.0.4
  google_fonts: ^2.1.0
  pedantic: ^1.11.0
  paginate_firestore: ^1.0.0-nullsafety.0

  # Authentication
  google_sign_in: ^5.0.3
  flutter_facebook_auth: ^3.3.3+1
  sign_in_with_apple: ^3.0.0 # no web
  kakao_flutter_sdk: ^0.6.3

  # State Management
  provider: ^5.0.0
  flutter_riverpod: ^0.14.0+3

  # Widgets
  flutter_slidable: ^1.0.0-dev.2
  fl_chart: ^0.36.1
  smooth_page_indicator: ^0.3.0-nullsafety.0
  circular_countdown_timer: ^0.2.0
  keyboard_actions: ^3.4.0
  flutter_rating_bar: ^4.0.0
  confetti: ^0.6.0-nullsafety
  numberpicker: ^2.1.1
  shimmer: ^2.0.0
  miniplayer: ^1.0.0+2
  font_awesome_flutter: ^9.0.0
  percent_indicator: ^3.3.0-nullsafety.1
  timer_count_down: ^2.0.1
  convex_bottom_bar: ^3.0.0
  youtube_player_flutter: ^8.0.0

  # Others
  flutter_cache_manager: ^3.0.2 # no web
  cached_network_image: ^3.0.0 # no web # no null safety
  email_validator: ^2.0.1
  password_strength: ^0.2.0
  timeago: ^3.0.2
  easy_localization: ^3.0.0
  mixpanel_flutter: ^1.1.0
dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: "assets/logos/herakles_logo.png"
  image_path_android: "assets/logos/herakles_logo.png"
  andriod: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "#121212"

flutter:
  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 300
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
    - family: menlo
      fonts:
        - asset: assets/fonts/MenloRegular.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/emojis/
flutter_intl:
  enabled: true
