name: workout_player
description: A new app that helps you workout better.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.21.0
  intl: ^0.17.0
  http: ^0.13.1
  firebase_storage: ^8.0.2
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  firebase_auth: ^1.0.2
  firebase_crashlytics: ^2.0.0 # no web
  firebase_analytics: ^7.1.1
  flutter_facebook_auth: ^3.3.2
  sign_in_with_apple: ^3.0.0 ## no web
  google_sign_in: ^5.0.1
  fl_chart: ^0.35.0
  google_fonts: ^2.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  logger: ^1.0.0
  persistent_bottom_nav_bar: ^4.0.2
  rxdart: ^0.26.0
  flutter_slidable: ^0.6.0-nullsafety.0
  circular_countdown_timer: ^0.2.0
  keyboard_actions: ^3.4.0
  flutter_cache_manager: ^3.0.1 # no web
  cached_network_image: ^3.0.0 # no web
  font_awesome_flutter: ^9.0.0
  pedantic: ^1.11.0
  paginate_firestore: ^1.0.0-nullsafety.0
  flutter_rating_bar: ^4.0.0
  confetti: ^0.6.0-nullsafety
  flutter_speed_dial: ^3.0.5
  numberpicker: ^2.0.1
  shimmer: ^2.0.0-nullsafety.0
  email_validator: ^2.0.1
  password_strength: ^0.2.0
  flutter_kakao_login: ^3.2.1
  dotted_line: ^3.0.0
  miniplayer: ^1.0.0+2
  timeago: ^3.0.2
dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/logos/playerh_logo.png"
  andriod: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "#000000"

flutter:
  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 300
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
    - family: menlo
      fonts:
        - asset: assets/fonts/MenloRegular.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/emojis/
flutter_intl:
  enabled: true
