name: workout_player
description: A new app that helps you workout better.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.2+7

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  intl: ^0.17.0
  http: ^0.13.0
  firebase_storage: ^8.0.0
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_crashlytics: ^1.0.0
  # firebase_analytics: ^7.1.0
  flutter_login_facebook: ^1.0.0-nullsafety.1
  sign_in_with_apple: ^3.0.0-nullsafety.0 
  google_sign_in: ^5.0.0
  # kakao_flutter_sdk: ^0.5.4
  fl_chart: ^0.20.1
  google_fonts: ^2.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  provider: ^5.0.0
  # flutter_bloc: ^6.1.1
  cupertino_icons: ^1.0.2
  # page_transition: ^1.1.7+3
  logger: ^1.0.0-nullsafety.0
  # shared_preferences: ^0.5.12+4
  persistent_bottom_nav_bar: ^3.1.0
  rxdart: ^0.26.0
  flutter_slidable: ^0.6.0-nullsafety.0
  circular_countdown_timer: ^0.0.8
  keyboard_actions: ^3.3.1+1
  flutter_cache_manager: ^3.0.0-nullsafety.1
  cached_network_image: ^3.0.0-nullsafety
  font_awesome_flutter: ^9.0.0-nullsafety
  pedantic: ^1.11.0
  paginate_firestore: ^1.0.0-nullsafety.0
  flutter_rating_bar: ^4.0.0
  confetti: ^0.6.0-nullsafety
#  material_floating_search_bar: ^0.2.6
#  flappy_search_bar: ^1.7.2
#  implicitly_animated_reorderable_list: ^0.3.2
#  get: ^3.24.0
#  modal_bottom_sheet: ^1.0.0+1
#  sleek_circular_slider: ^1.2.0+web
#  percent_indicator: ^2.1.9
#  table_calendar: ^2.3.3


dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/logos/playerh_logo.png"
  andriod: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "#000000"

flutter:
  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 300
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
